template = ""
rev_id = 4
template_sha = "156a8b834dacf74fc905a1ee460fe5eabb9556c6"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "se"
__UND2C_TRG__ = "smn"
__UNDEFINED_SOURCE__ = "North Sámi"
__UNDEFINED_TARGET__ = "Inari Sámi"
__UND_SRC__ = "sme"
__UND_TRG__ = "smn"
